// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resource/preview/enable": {
    params: {};
  };
  "/resource/preview/disable": {
    params: {};
  };
  "/studio/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resource/preview/enable" | "/resource/preview/disable" | "/studio/*" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/resource/preview/enable.ts": {
    id: "routes/resource/preview/enable";
    page: "/resource/preview/enable";
  };
  "routes/resource/preview/disable.ts": {
    id: "routes/resource/preview/disable";
    page: "/resource/preview/disable";
  };
  "routes/studio.tsx": {
    id: "routes/studio";
    page: "/studio/*";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};